### ISSUE TITLE
No rewards for crate even though I added them?

### ISSUE THREAD

**Issue by itzTheMeow** [nulli0n/GoldenCrates#15]
I'm using spigot 1.16.4 and the latest version of the plugin. - [My crate.yml](https://paste.gg/p/anonymous/18b27d3fe5de4d77b9431426e08c872f)
I added rewards here:
![image](https://user-images.githubusercontent.com/50887230/104205887-eabc3900-53fc-11eb-9334-0c62d01aa533.png)
but theres nothing inside when I open it.
![image](https://user-images.githubusercontent.com/50887230/104205954-fc9ddc00-53fc-11eb-9ed5-094a3d784164.png)
and the chat says I won blank
![image](https://user-images.githubusercontent.com/50887230/104205995-0aebf800-53fd-11eb-84b4-37894ebe17ef.png)

**Comment by itzTheMeow** [comment]
I now notice this error in the console:
```
[13:46:48] [Server thread/WARN]: [GoldenCrates] Task #2770 for GoldenCrates v3.10.0 generated an exception
java.lang.NoSuchMethodError: su.nexmedia.engine.utils.random.Rnd.get(Ljava/util/Map;)Ljava/lang/Object;
        at su.nightexpress.goldencrates.manager.crate.Crate.rollReward(Crate.java:448) ~[?:?]
        at su.nightexpress.goldencrates.manager.template.CrateTemplate$SpinTask.spinReward(CrateTemplate.java:357) ~[?:?]
        at su.nightexpress.goldencrates.manager.template.CrateTemplate$SpinTask.run(CrateTemplate.java:346) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]```

**Comment by nulli0n** [comment]
Use both jars

**Comment by itzTheMeow** [comment]
both jars? im using goldencrates and nexengine (im assuming the nexengine included with goldenenchants is the same as goldencrates one)
