### ISSUE TITLE
3.11.0 enabling error

### ISSUE THREAD

**Issue by sifexeu** [nulli0n/GoldenCrates#35]
When i start up my 1.16.4 spigot server with the newest version i get this error

Error occurred while enabling GoldenCrates v3>
java.lang.NoSuchMethodError: 'void su.nexmedia.engine.config.api.ILangTemplate.>
        at su.nightexpress.goldencrates.config.Lang.<init>(Lang.java:12) ~[?:?]
        at su.nightexpress.goldencrates.GoldenCrates.setConfig(GoldenCrates.jav>
        at su.nexmedia.engine.config.ConfigManager.setup(ConfigManager.java:32)>
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:164) ~[?:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:87) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[>
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoade>
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManag>
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer>
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServe>
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftSer>
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.j>
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java>
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServ>
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by nulli0n** [comment]
Use both .jar
