### ISSUE TITLE
this error appears when a crate is opened

### ISSUE THREAD

**Issue by Porkason** [nulli0n/GoldenCrates#6]
>.... [22:44:25 WARN]: [GoldenCrates] Task #24666 for GoldenCrates v3.10.0 generated an exception
java.lang.NoSuchMethodError: 'java.lang.Object su.nexmedia.engine.utils.random.Rnd.get(java.util.Map)'
at su.nightexpress.goldencrates.manager.crate.Crate.rollReward(Crate.java:448) ~[?:?]
at su.nightexpress.goldencrates.manager.template.CrateTemplate$SpinTask.spinReward(CrateTemplate.java:357) ~[?:?]
at su.nightexpress.goldencrates.manager.template.CrateTemplate$SpinTask.run(CrateTemplate.java:346) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-253]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-253]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by nulli0n** [comment]
Maybe use both .jars from the .zip
